### ISSUE TITLE
Stop printing log messages on stderr

### ISSUE THREAD

**Issue by CuiCui66** [vincent-hugot/qtest#57]
I'm using qtest as part of `dune` and it is very annoying for me that qtest prints some log output on `stderr` when everything is going normally. For example 

```
Extraction : `src/modulename.ml' Done.
```
Either this output should be entirely suppressed or a `--quiet` option could be added to suppress it.

**Comment by c-cube** [comment]
would you mind testing on master?

**Comment by CuiCui66** [comment]
It stopped printing `Extraction : ` and `Done.` but it still prints the name of the processed files in between.

**Comment by c-cube** [comment]
my bad. should be fixed now.

**Comment by CuiCui66** [comment]
Seems good to me! Thank you very much!
