### ISSUE TITLE
Where are printers documented?

### ISSUE THREAD

**Issue by kwshi** [vincent-hugot/qtest#58]
The documentation mentions using `Q.Print` to define printers, and I see code in c-cube/ocaml-containers that references things like `Q.Print.list` and `Q.Print.int` to define printers, but I can't seem to find an exhaustive reference/documentation on all the printers defined by `Q.Print`.  In fact, I can't even seem to find any source code for the `Q.Print` module.  What am I missing?

**Comment by c-cube** [comment]
Q is an alias to QCheck, a dependency of qtest. The documentation for printers is defined there :-)

**Comment by kwshi** [comment]
Ah!  Thanks.
